apiVersion: v1
kind: Service
metadata:
  name: gravitino
  namespace: datalakehouse
spec:
  type: NodePort
  selector:
    app: gravitino
  ports:
    - name: rest
      port: 9010
      targetPort: 9010
      nodePort: 30910