apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  namespace: datalakehouse
spec:
  type: NodePort
  ports:
    - name: rpc
      port: 6123
    - name: blob
      port: 6124
    - name: query
      port: 6125
    - name: ui
      port: 8081
      nodePort: 30900
  selector:
    app: flink
    component: jobmanager