apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: s3api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: webui
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30801