apiVersion: v1
kind: Service
metadata:
  name: nessie-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 19120
      targetPort: 19120
      nodePort: 30920
  selector:
    app: nessie