apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: datalakehouse
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
    - name: pgadmin
      port: 80
      nodePort: 30200