apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: datalakehouse
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      nodePort: 30432