apiVersion: starrocks.com/v1
kind: StarRocksCluster
metadata:
  name: starrocks
  namespace: query
spec:
  starRocksFeSpec:
    image: starrocks/fe-ubuntu:latest
    replicas: 1
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi
    service:
      type: NodePort
  starRocksBeSpec:
    image: starrocks/be-ubuntu:latest
    replicas: 1
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 2Gi