apiVersion: v1
kind: PersistentVolume
metadata:
  name: flinkplugin-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt/data/flink/plugins
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
  persistentVolumeReclaimPolicy: Retain
