apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: datalakehouse
  labels:
    type: local
    app: minio
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/minio
  persistentVolumeReclaimPolicy: Retain
