apiVersion: v1
kind: PersistentVolume
metadata:
  name: nessie-pv
  labels:
    type: local
    app: nessie
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/nessie
  persistentVolumeReclaimPolicy: Retain