apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc
  namespace: datalakehouse
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
